# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- integration

pool:
  vmImage: 'ubuntu-latest'

#git -c http.extraheader="AUTHORIZATION: basic $PAT" push origin
steps:

- script: |
    git switch master
    git merge origin/integration
    echo "https://$PAT:x-oauth-basic@github.com" >> "$HOME\.git-credentials"
    git config --global user.email "jonathan.melly@gmail.com"
    git config --global --add url."git@github.com:".insteadOf "https://github.com/"
    git push
  env:
    PAT: '$(System.AccessToken)'
  displayName: 'Run a multi-line script'
  


