# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  tags:
    include:
    - v*

pool:
  vmImage: 'windows-latest'

steps:

#CREATE BINARY (publish)
- task: DotNetCoreCLI@2
  displayName: 'Publish windows'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'app/app.csproj'
    arguments: '-c Release -r windows-x64 -p:PublishReadyToRun=true -o $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true
    modifyOutputPath: false

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'cosmos-win64'
    publishLocation: 'Container'

