# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  tags:
    include:
    - v*

variables:
  test: 'test'
  zip: true

stages:

- stage: Dummy
  jobs:
    - job: Dummy

- stage: Windows
  dependsOn: Dummy
  pool:
    vmImage: 'windows-latest'
  jobs:
  - job: WindowsBuild
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Publish windows'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: 'app/app.csproj'
        arguments: '-c Release -r win-x64 -p:PublishReadyToRun=true -o $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true
        modifyOutputPath: false
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'cosmos-win64'
        publishLocation: 'Container'

- stage: Linux
  dependsOn: Dummy
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: LinuxBuild
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Publish ubuntu linux'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: 'app/app.csproj'
        arguments: '-c Release -r linux-x64 -p:PublishReadyToRun=true -o $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true
        modifyOutputPath: false
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'cosmos-linux64'
        publishLocation: 'Container'

- stage: releasenotes
  dependsOn: 
    - Windows
    - Linux
  pool:
    vmImage: 'windows-latest'
  jobs:
  - job: releasenotes
    steps:
    - task: 'JonathanMelly.BM-VSTS-XplatGenerateReleaseNotes-DEV.XplatGenerate-Release-Notes.XplatGenerateReleaseNotes@2'
      displayName: 'Generate Release Notes based on Release Comparision API'
      inputs:
        outputfile: '$(Agent.TempDirectory)\releasenotes.md'
        templateLocation: InLine
        inlinetemplate:  '# :rocket: Nouveautés'
        alsoGatherDataFromReleaseApi: false

    - task: DownloadPipelineArtifact@2
      displayName: 'Download Pipeline Artifact'
      inputs:
        targetPath: '$(Pipeline.Workspace)_artifacts/'

    - task: GitHubRelease@1
      displayName: 'GitHub release (create)'
      inputs:
        gitHubConnection: 'github repo release'
        title: '$(Build.SourceVersion)'
        releaseNotesFilePath: '$(Agent.TempDirectory)\releasenotes.md'
        assets: '$(Pipeline.Workspace)_artifacts/'

        addChangeLog: false







