# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  tags:
    include:
    - v*

variables:
  test: 'test'
  zip: true

stages:
- stage: Windows
  pool:
    vmImage: 'windows-latest'
  jobs:
  - job: WindowsBuild
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Publish windows'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: 'app/app.csproj'
        arguments: '-c Release -r windows-x64 -p:PublishReadyToRun=true -o $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true
        modifyOutputPath: false
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'cosmos-win64'
        publishLocation: 'Container'

- stage: Linux
  pool:
    vmImage: 'linux-latest'
  jobs:
  - job: LinuxBuild
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Publish linux'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: 'app/app.csproj'
        arguments: '-c Release -r linux-x64 -p:PublishReadyToRun=true -o $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true
        modifyOutputPath: false
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'cosmos-linux64'
        publishLocation: 'Container'





