# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  tags:
    include:
    - v*

pool:
  vmImage: 'windows-latest'

steps:

#CREATE BINARY (publish)
- task: DotNetCoreCLI@2
  displayName: 'publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'app/app.csproj'
    zipAfterPublish: true
    modifyOutputPath: false



